dataset:
  name: mnist
  root: "./data"
  num_workers: 2
  img_height: 28
  img_width: 28
  in_channel: 1
  n_class: 10
  transform: basic
  shuffle: 0

criterion:
  name: ce

optimizer:
  name: adam
  lr: 0.002
  weight_decay: 0.0001

scheduler:
  name: cosine
  lr_gamma: 0.99
  lr_min: 0

run:
  experiment: "default"
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  random_state: 42
  log_interval: 200
  train_noise: 0

quantize:
  weight_bit: 7
  input_bit: 7
  v_pi: 4.36
  v_max: 10.8

morr:
  config: MORRConfig_20um_MQ
  trainable_bias: 0
  trainable_scale: 0
  morr_init: 0

checkpoint:
  save_best_model_k: 3
  checkpoint_dir: "mnist/cnn/pretrain"
  model_comment: ""
  resume: 0
  restore_checkpoint: ""
  no_linear: 0

model:
  name: "MORR_CLASS_CNN"
  mode: "weight"
  # kernel_list: [32, 32]
  # kernel_size_list: [5, 5]
  # hidden_list: []
  # block_list: [3, 3, 3]
  # stride_list: [2, 2]
  # padding_list: [1, 1]
  # pool_out_size: 5
  kernel_list: [64, 64, 128, 128, 256, 256, 256, 512, 512, 512, 512, 512, 512]
  maxpool_kernel_list: ['M', 'M', 'M', 'M', 'M']
  kernel_size_list:  [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  hidden_list:  [4096, 4096]   
  block_list:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  stride_list: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  padding_list: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  pool_out_size: 7
  act: relu
  act_thres: 10
  norm: bn

debug:
  verbose: 1

